

/* Blogs */

####
DELETE http://localhost:3001/api/blogs

####
GET http://localhost:3001/api/blogs

#### Example of Valid 
POST http://localhost:3001/api/blogs 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhhcmkgTGFsIiwiaWQiOiI2NzZlMmQ2Y2M4YTg2NDBmOWYyMmI1ZGMiLCJpYXQiOjE3MzUyNzM4ODh9.5WQenVoUK8Nk29T7zX4wpySSrYuda8c0rbuaitqiyko
Content-Type: application/json

{
  "title": "SEO",
  "author": "Kali Prasad",
  "url": "https://example.com/SEO",
  "likes": 0
}


#### Example of invalid Token
POST http://localhost:3001/api/blogs 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhhcmkgTGFsIiwiaWQiOiI2NzZlMmQ2Y2M4YTg2NDBmOWYyMmI1ZGMiLCJpYXQiOjE3MzUyNzM4ODh9.5WQenVoUK8Nk29T7zX4wpySSrYuda8caaaaaaaa
Content-Type: application/json

{
  "title": "SEO",
  "author": "Kali Prasad",
  "url": "https://example.com/SEO",
  "likes": 0
}



####
PUT http://localhost:3001/api/persons/674dda8d887c653059821956
Content-Type: application/json

{
    "name": "Kir",
    "number": "88888888"
}




/* Users */

####
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "Hari Lal",
    "name": "Hari Lal",
    "password": "ASDfg@"
}


###
GET http://localhost:3001/api/users




/* Login */

####
POST http://localhost:3001/api/login
Content-Type: application/json

{
     "username": "Hari Lal",
    "password": "ASDfg@"
}


###
GET http://localhost:3001/api/users