

/* Blogs */

####
DELETE http://localhost:3001/api/blogs

####
GET http://localhost:3001/api/blogs

####
POST http://localhost:3001/api/blogs 
Content-Type: application/json

{
  "title": "Web Browser",
  "author": "Lalu Prasad",
  "url": "https://example.com/node-architecture",
  "likes": 10,
  "userId": "676c3430734a264aaae53e3f"
}



####
PUT http://localhost:3001/api/persons/674dda8d887c653059821956
Content-Type: application/json

{
    "name": "Kir",
    "number": "88888888"
}




/* Users */

####
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "mluukkai",
    "name": "Matti Luukkai",
    "password": "qazwsx@"
}


###
GET http://localhost:3001/api/users




/* Login */

####
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "mluukkai",
    "password": "qazwsx@"
}


###
GET http://localhost:3001/api/users